### ISSUE TITLE
Crash while pressing ESC (query SQL tool)

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#88] opened 2021-12-21 20:40 UTC
Hello @little-brother 

sqlite-gui 1.6.5 (x64)
Windows 10

Paste this SQL code (after creating a new database):
create table images
(id integer not null primary key,
name text,
image blob);

Now write this code:
insert into images values ( 
If you press ESC (on your keyboard) sqlite-gui always crashes.
just put your mouse cursor **after the bracket (** and press ESC
I am working with an ASUS notebook (italian layout).

See this video steps:

https://user-images.githubusercontent.com/33007383/146994132-c21feceb-211a-489e-9774-27e21f2fc508.mp4

Reproduced easily every time I try again with this database (stored on OneDrive):
https://1drv.ms/u/s!AjEV_9wBPHINgoYQW85Qr3vvSxqNJg?e=wVfyIi

**EDIT:** never mind the database and the SQL abovementioned. 
Actually **it suffices to press ESC** and sqlite-gui always crashes (sql window) :-)

**Comment by little-brother** [comment] 2021-12-21 21:00
If you rerun the app, is a code restored? If your answer is yes, then it's not a bug.
The quit by escape is a default behaviour. You can change it in Settings.
P.S. Thanks for the detailed report.

**Comment by SilvioGrosso** [comment] 2021-12-21 21:11
> If you rerun the app, is a code restored? If your answer is yes, then it's not a bug.

Yes. It is restored.
I have also noticed the Settings now :-)

I have imagined it was a bug because the application "crashed" without any warning (e.g. _do yo want to really close this application_ or something like that...) :-)

**Comment by jungle-boogie** [comment] 2021-12-22 01:10
> I have imagined it was a bug because the application "crashed" without
any warning (e.g. *do yo want to really close this application*or something
like that...) :-)

That is also expected.

**Comment by jungle-boogie** [comment] 2021-12-22 18:17
See https://github.com/little-brother/sqlite-gui/issues/30

**Comment by little-brother** [comment] 2022-02-10 21:02
The option was added.

**Closed by little-brother** 2022-02-10 21:02 UTC
